// KOVA Demo Data — 5 Verticals, Full Data Points
// Real Estate · Healthcare · Manufacturing · Construction · Professional Services

export const VERTICAL_CONFIG: Record<string, any> = {
  real_estate: {
    label: "Real Estate", color: "#00C896", icon: "🏠",
    stages: ["New Lead","Listing Interest","Showing Scheduled","Offer Stage","Under Contract","Closed"],
    scoreWeights: { fit:0.30, intent:0.35, timing:0.20, value:0.15 },
  },
  healthcare: {
    label: "Healthcare", color: "#3B9EFF", icon: "🏥",
    stages: ["New Patient","Consultation Booked","Assessment","Treatment Plan","Active Patient","Retained"],
    scoreWeights: { fit:0.35, intent:0.25, timing:0.20, value:0.20 },
  },
  manufacturing: {
    label: "Manufacturing", color: "#A78BFA", icon: "🏭",
    stages: ["Prospect","RFQ Received","Estimating","Quote Sent","PO Received","In Production","Shipped"],
    scoreWeights: { fit:0.25, intent:0.30, timing:0.25, value:0.20 },
  },
  construction: {
    label: "Construction", color: "#F59E0B", icon: "🔨",
    stages: ["Lead In","Estimate Requested","Estimate Sent","Follow-Up","Contract Signed","In Progress","Punch List","Closed"],
    scoreWeights: { fit:0.25, intent:0.35, timing:0.25, value:0.15 },
  },
  professional_services: {
    label: "Professional Services", color: "#EC4899", icon: "💼",
    stages: ["Inquiry","Discovery Call","Proposal Sent","Engagement Letter","Onboarding","Active Client","Retained"],
    scoreWeights: { fit:0.30, intent:0.25, timing:0.20, value:0.25 },
  },
};

export const ALL_VERTICALS = Object.keys(VERTICAL_CONFIG);

// ── COMPANIES ────────────────────────────────────────────────────────────────
export const COMPANIES: any[] = [
  // REAL ESTATE
  {
    id:1, name:"Apex Realty Group", vertical:"real_estate",
    industry:"Residential Brokerage", revenue:"$2,400,000", employees:14,
    phone:"(305) 488-2200", email:"office@apexrealtygroup.com",
    address:"2400 Brickell Ave, Suite 600", city:"Miami", state:"FL", zip:"33129",
    website:"apexrealtygroup.com", linkedin:"linkedin.com/company/apex-realty-group",
    founded:"2016", contacts:3, deals:4, notes:"Top residential brokerage in Brickell. Referral partner. Expanding to Broward County Q3.",
  },
  {
    id:2, name:"Suncoast Properties", vertical:"real_estate",
    industry:"Full-Service Brokerage", revenue:"$5,100,000", employees:28,
    phone:"(813) 555-0180", email:"info@suncoastproperties.com",
    address:"4200 Cypress St, Suite 200", city:"Tampa", state:"FL", zip:"33607",
    website:"suncoastproperties.com", linkedin:"linkedin.com/company/suncoast-properties",
    founded:"2011", contacts:5, deals:7, notes:"Largest brokerage account. Multiple locations. Key decision maker is David Park.",
  },
  {
    id:3, name:"Clearwater Investments LLC", vertical:"real_estate",
    industry:"Investment Portfolio", revenue:"$12,000,000", employees:6,
    phone:"(727) 555-0244", email:"admin@clearwaterinv.com",
    address:"900 Harbor View Dr", city:"Clearwater", state:"FL", zip:"33767",
    website:"clearwaterinvestments.com", linkedin:"",
    founded:"2009", contacts:2, deals:3, notes:"Passive investor group. Manages 22 residential units. High value, low touch needed.",
  },
  // HEALTHCARE
  {
    id:4, name:"Okafor Family Medicine", vertical:"healthcare",
    industry:"Primary Care Practice", revenue:"$3,200,000", employees:18,
    phone:"(312) 555-0195", email:"admin@okafarfamilymed.com",
    address:"1720 N Michigan Ave, Suite 310", city:"Chicago", state:"IL", zip:"60611",
    website:"okaformed.com", linkedin:"linkedin.com/company/okafor-family-medicine",
    founded:"2014", contacts:2, deals:2, notes:"Independent practice. Owner Dr. Emeka Okafor looking to scale patient acquisition. Strong referral base.",
  },
  {
    id:5, name:"Sunrise Dental Group", vertical:"healthcare",
    industry:"Dental — Multi-Location", revenue:"$8,400,000", employees:52,
    phone:"(214) 555-0162", email:"corporate@sunrisedentalgroup.com",
    address:"8900 Preston Rd, Suite 400", city:"Dallas", state:"TX", zip:"75225",
    website:"sunrisedentalgroup.com", linkedin:"linkedin.com/company/sunrise-dental-group",
    founded:"2008", contacts:3, deals:3, notes:"6 locations across DFW. CEO Marcus Jimenez managing aggressive expansion. High value account.",
  },
  {
    id:6, name:"Coastal Behavioral Health", vertical:"healthcare",
    industry:"Behavioral Health", revenue:"$1,900,000", employees:12,
    phone:"(813) 555-0310", email:"info@coastalbehavioral.com",
    address:"3100 S MacDill Ave, Suite 115", city:"Tampa", state:"FL", zip:"33629",
    website:"coastalbehavioral.com", linkedin:"",
    founded:"2019", contacts:2, deals:1, notes:"Newer practice. Director is building out intake pipeline. Patient retention is main challenge.",
  },
  // MANUFACTURING
  {
    id:7, name:"Harmon Industrial Supply", vertical:"manufacturing",
    industry:"Industrial Supply & Distribution", revenue:"$14,000,000", employees:85,
    phone:"(216) 555-0148", email:"sales@harmonindustrial.com",
    address:"4800 Lakeside Ave E", city:"Cleveland", state:"OH", zip:"44114",
    website:"harmonindustrial.com", linkedin:"linkedin.com/company/harmon-industrial",
    founded:"2001", contacts:2, deals:2, notes:"VP Greg Harmon is the decision maker. Long procurement cycles. High LTV if converted.",
  },
  {
    id:8, name:"Pacific Fabrication Co.", vertical:"manufacturing",
    industry:"Metal Fabrication", revenue:"$24,000,000", employees:220,
    phone:"(503) 555-0290", email:"info@pacificfab.com",
    address:"7200 NE Columbia Blvd", city:"Portland", state:"OR", zip:"97218",
    website:"pacificfab.com", linkedin:"linkedin.com/company/pacific-fabrication",
    founded:"1994", contacts:3, deals:4, notes:"Largest manufacturing account. CFO Lisa Chen owns the vendor relationship. 12-month contract cycle.",
  },
  {
    id:9, name:"Apex Composite Materials", vertical:"manufacturing",
    industry:"Aerospace Composites", revenue:"$6,800,000", employees:45,
    phone:"(860) 555-0174", email:"procurement@apexcomposites.com",
    address:"300 Griffin Rd", city:"Hartford", state:"CT", zip:"06101",
    website:"apexcomposites.com", linkedin:"linkedin.com/company/apex-composites",
    founded:"2006", contacts:2, deals:1, notes:"Defense subcontractor. Slow cycle but high precision and margin. Procurement lead is the key contact.",
  },
  // CONSTRUCTION
  {
    id:10, name:"Storm Shield Roofing & Restoration", vertical:"construction",
    industry:"Roofing & Storm Restoration", revenue:"$3,800,000", employees:22,
    phone:"(813) 555-0420", email:"office@stormshieldroofing.com",
    address:"1840 E Hillsborough Ave", city:"Tampa", state:"FL", zip:"33610",
    website:"stormshieldroofing.com", linkedin:"linkedin.com/company/storm-shield-roofing",
    founded:"2015", contacts:3, deals:5, notes:"Owner Marcus Rodriguez is hands-on. High volume of insurance claims work after storm season. Agent-guided quoting is perfect fit.",
  },
  {
    id:11, name:"Gulf Coast HVAC Solutions", vertical:"construction",
    industry:"HVAC Installation & Service", revenue:"$2,200,000", employees:16,
    phone:"(727) 555-0385", email:"service@gulfcoasthvac.com",
    address:"5500 Park Blvd N", city:"Pinellas Park", state:"FL", zip:"33781",
    website:"gulfcoasthvac.com", linkedin:"",
    founded:"2017", contacts:3, deals:4, notes:"Residential and light commercial. Owner Derek Mills focused on growing service agreements. Strong referral pipeline.",
  },
  {
    id:12, name:"Precision Plumbing + Electric", vertical:"construction",
    industry:"Plumbing & Electrical Contracting", revenue:"$1,600,000", employees:11,
    phone:"(727) 555-0298", email:"dispatch@precisionpe.com",
    address:"2210 38th Ave N", city:"St. Petersburg", state:"FL", zip:"33713",
    website:"precisionplumbingelectric.com", linkedin:"",
    founded:"2020", contacts:2, deals:3, notes:"Younger company with strong Nextdoor presence. Owner Kevin Patel wants to systematize quoting. High growth potential.",
  },
  // PROFESSIONAL SERVICES
  {
    id:13, name:"Meridian Law Group", vertical:"professional_services",
    industry:"Business & Real Estate Law", revenue:"$4,600,000", employees:19,
    phone:"(813) 555-0512", email:"info@meridianlaw.com",
    address:"101 E Kennedy Blvd, Suite 1800", city:"Tampa", state:"FL", zip:"33602",
    website:"meridianlaw.com", linkedin:"linkedin.com/company/meridian-law-group",
    founded:"2012", contacts:2, deals:2, notes:"Managing Partner Amanda Chen drives all business development. Referral-heavy. Long client retention cycles.",
  },
  {
    id:14, name:"Atlas Wealth Advisors", vertical:"professional_services",
    industry:"Financial Advisory & Wealth Mgmt", revenue:"$7,200,000", employees:14,
    phone:"(727) 555-0630", email:"office@atlaswealthadvisors.com",
    address:"360 Central Ave, Suite 1600", city:"St. Petersburg", state:"FL", zip:"33701",
    website:"atlaswealthadvisors.com", linkedin:"linkedin.com/company/atlas-wealth-advisors",
    founded:"2010", contacts:3, deals:3, notes:"AUM-based model. Patricia Okafor runs all client acquisition. Compliance-sensitive. High LTV per client.",
  },
  {
    id:15, name:"Summit CPA & Advisory", vertical:"professional_services",
    industry:"Accounting & Business Advisory", revenue:"$2,900,000", employees:12,
    phone:"(813) 555-0577", email:"hello@summitcpa.com",
    address:"4830 W Kennedy Blvd, Suite 600", city:"Tampa", state:"FL", zip:"33609",
    website:"summitcpa.com", linkedin:"linkedin.com/company/summit-cpa",
    founded:"2016", contacts:2, deals:2, notes:"Serves small business owners across Tampa Bay. Principal James Thornton looking to scale without adding headcount.",
  },
];

// ── CONTACTS ────────────────────────────────────────────────────────────────
export const CONTACTS: any[] = [
  // REAL ESTATE
  {
    id:1, firstName:"Sarah", lastName:"Mitchell", fn:"Sarah", ln:"Mitchell",
    name:"Sarah Mitchell", title:"Managing Broker", company:"Apex Realty Group",
    email:"s.mitchell@apexrealtygroup.com", phone:"(305) 555-0142",
    address:"2400 Brickell Ave, Suite 600", city:"Miami", state:"FL", zip:"33129",
    website:"apexrealtygroup.com", linkedin:"linkedin.com/in/sarahmitchell-re",
    vertical:"real_estate", source:"Google Ads", stage:"Customer", status:"Active",
    score:87, tags:["VIP","Referral Partner","High Value"],
    lifetimeValue:48600, dealCount:4, quoteCount:6, avgDealSize:12150,
    lastContact:"Jun 2, 2026", firstContact:"Mar 14, 2024", lastPurchase:"May 28, 2026",
    nextAction:"Send Coral Gables staging proposal", buyProbability:72,
    preferredChannel:"Email", responseTime:"< 2 hours",
    emailsOpened:34, emailsSent:42, meetingsHeld:8, quotesAccepted:4, quotesSent:6,
    pageVisits:156, lastPageVisited:"Pricing page", referralSource:"Google Ads → Landing Page",
    notes:"Expanding to Broward County Q3. Volume pricing conversation planned for July.",
  },
  {
    id:2, firstName:"David", lastName:"Park", fn:"David", ln:"Park",
    name:"David Park", title:"Broker-Owner", company:"Suncoast Properties",
    email:"d.park@suncoastproperties.com", phone:"(813) 555-0188",
    address:"4200 Cypress St, Suite 200", city:"Tampa", state:"FL", zip:"33607",
    website:"suncoastproperties.com", linkedin:"linkedin.com/in/davidparkre",
    vertical:"real_estate", source:"Referral — Sarah Mitchell", stage:"Active Client", status:"Active",
    score:91, tags:["VIP","Multi-Location","High Volume"],
    lifetimeValue:72400, dealCount:7, quoteCount:9, avgDealSize:10343,
    lastContact:"Jun 3, 2026", firstContact:"Nov 8, 2023", lastPurchase:"Jun 1, 2026",
    nextAction:"Quarterly review — 3 upcoming listings to stage", buyProbability:85,
    preferredChannel:"Phone", responseTime:"Same day",
    emailsOpened:28, emailsSent:31, meetingsHeld:14, quotesAccepted:7, quotesSent:9,
    pageVisits:204, lastPageVisited:"Portfolio gallery", referralSource:"Sarah Mitchell referral",
    notes:"Primary contact for all Suncoast staging work. Prefers quick calls over long emails.",
  },
  {
    id:3, firstName:"Rachel", lastName:"Torres", fn:"Rachel", ln:"Torres",
    name:"Rachel Torres", title:"Investment Director", company:"Clearwater Investments LLC",
    email:"r.torres@clearwaterinv.com", phone:"(727) 555-0251",
    address:"900 Harbor View Dr", city:"Clearwater", state:"FL", zip:"33767",
    website:"clearwaterinvestments.com", linkedin:"linkedin.com/in/racheltorres-inv",
    vertical:"real_estate", source:"LinkedIn Outreach", stage:"Customer", status:"Active",
    score:74, tags:["Investor","Portfolio Client","Slow Cycle"],
    lifetimeValue:31200, dealCount:3, quoteCount:4, avgDealSize:10400,
    lastContact:"May 22, 2026", firstContact:"Jan 6, 2024", lastPurchase:"Apr 14, 2026",
    nextAction:"Check in on Harbor View unit — lease renewal coming up", buyProbability:58,
    preferredChannel:"Email", responseTime:"2–3 business days",
    emailsOpened:19, emailsSent:26, meetingsHeld:4, quotesAccepted:3, quotesSent:4,
    pageVisits:67, lastPageVisited:"Investment portfolio services", referralSource:"LinkedIn cold outreach",
    notes:"Passive investor. Makes decisions slowly but always pays promptly. Key is to stay top of mind.",
  },
  // HEALTHCARE
  {
    id:4, firstName:"Emeka", lastName:"Okafor", fn:"Emeka", ln:"Okafor",
    name:"Dr. Emeka Okafor", title:"Owner & Physician", company:"Okafor Family Medicine",
    email:"dr.okafor@okaformed.com", phone:"(312) 555-0197",
    address:"1720 N Michigan Ave, Suite 310", city:"Chicago", state:"IL", zip:"60611",
    website:"okaformed.com", linkedin:"linkedin.com/in/emekaokafor",
    vertical:"healthcare", source:"Medical Conference — AMA 2025", stage:"Active Client", status:"Active",
    score:82, tags:["Owner-Operated","Growth Stage","Referral Source"],
    lifetimeValue:28400, dealCount:2, quoteCount:3, avgDealSize:14200,
    lastContact:"May 30, 2026", firstContact:"Sep 18, 2025", lastPurchase:"Apr 2, 2026",
    nextAction:"Share patient acquisition case study — he asked at last meeting", buyProbability:68,
    preferredChannel:"Email", responseTime:"24–48 hours",
    emailsOpened:22, emailsSent:29, meetingsHeld:5, quotesAccepted:2, quotesSent:3,
    pageVisits:98, lastPageVisited:"Healthcare vertical overview", referralSource:"AMA Conference 2025",
    notes:"Thoughtful decision maker. Wants to see ROI data before committing. Referred two colleagues.",
  },
  {
    id:5, firstName:"Marcus", lastName:"Jimenez", fn:"Marcus", ln:"Jimenez",
    name:"Marcus Jimenez", title:"CEO", company:"Sunrise Dental Group",
    email:"m.jimenez@sunrisedentalgroup.com", phone:"(214) 555-0165",
    address:"8900 Preston Rd, Suite 400", city:"Dallas", state:"TX", zip:"75225",
    website:"sunrisedentalgroup.com", linkedin:"linkedin.com/in/marcusjimenez-dental",
    vertical:"healthcare", source:"Paid Search — Google", stage:"Customer", status:"Active",
    score:94, tags:["Multi-Location","High Value","Decision Maker"],
    lifetimeValue:86500, dealCount:3, quoteCount:4, avgDealSize:28833,
    lastContact:"Jun 1, 2026", firstContact:"Jul 24, 2025", lastPurchase:"May 15, 2026",
    nextAction:"Proposal for locations 4, 5, 6 expansion package", buyProbability:88,
    preferredChannel:"Video Call", responseTime:"< 1 hour",
    emailsOpened:41, emailsSent:44, meetingsHeld:11, quotesAccepted:3, quotesSent:4,
    pageVisits:287, lastPageVisited:"Enterprise pricing", referralSource:"Google Ads — dental marketing",
    notes:"Moving fast on expansion. Has budget authority. Wants everything turnkey.",
  },
  {
    id:6, firstName:"Lisa", lastName:"Greenfield", fn:"Lisa", ln:"Greenfield",
    name:"Dr. Lisa Greenfield", title:"Practice Director", company:"Coastal Behavioral Health",
    email:"l.greenfield@coastalbehavioral.com", phone:"(813) 555-0312",
    address:"3100 S MacDill Ave, Suite 115", city:"Tampa", state:"FL", zip:"33629",
    website:"coastalbehavioral.com", linkedin:"linkedin.com/in/lisagreenfield-bh",
    vertical:"healthcare", source:"Tampa Chamber Referral", stage:"Proposal Sent", status:"Active",
    score:63, tags:["Newer Practice","Budget Conscious","Warm Lead"],
    lifetimeValue:8200, dealCount:1, quoteCount:2, avgDealSize:8200,
    lastContact:"May 28, 2026", firstContact:"Feb 11, 2026", lastPurchase:"Mar 20, 2026",
    nextAction:"Follow up on intake automation proposal — 14 days no response", buyProbability:44,
    preferredChannel:"Phone", responseTime:"3–5 business days",
    emailsOpened:9, emailsSent:18, meetingsHeld:3, quotesAccepted:1, quotesSent:2,
    pageVisits:44, lastPageVisited:"Behavioral health template library", referralSource:"Tampa Chamber of Commerce",
    notes:"Decision is committee-based. Slow mover but genuinely interested. Budget is tight.",
  },
  // MANUFACTURING
  {
    id:7, firstName:"Greg", lastName:"Harmon", fn:"Greg", ln:"Harmon",
    name:"Greg Harmon", title:"VP Operations", company:"Harmon Industrial Supply",
    email:"g.harmon@harmonindustrial.com", phone:"(216) 555-0150",
    address:"4800 Lakeside Ave E", city:"Cleveland", state:"OH", zip:"44114",
    website:"harmonindustrial.com", linkedin:"linkedin.com/in/gregharmon-ops",
    vertical:"manufacturing", source:"Trade Show — IMTS 2025", stage:"Negotiation", status:"Active",
    score:78, tags:["Long Cycle","High LTV","Technical Buyer"],
    lifetimeValue:168000, dealCount:2, quoteCount:3, avgDealSize:84000,
    lastContact:"May 24, 2026", firstContact:"Oct 4, 2025", lastPurchase:"Feb 28, 2026",
    nextAction:"Send revised SLA terms — requested 90-day pilot extension", buyProbability:61,
    preferredChannel:"Email", responseTime:"2–3 business days",
    emailsOpened:14, emailsSent:22, meetingsHeld:6, quotesAccepted:2, quotesSent:3,
    pageVisits:78, lastPageVisited:"ERP integration overview", referralSource:"IMTS 2025 Trade Show",
    notes:"Procurement decisions go through a 3-person committee. Greg is the champion. CFO is the blocker.",
  },
  {
    id:8, firstName:"Lisa", lastName:"Chen", fn:"Lisa", ln:"Chen",
    name:"Lisa Chen", title:"CFO", company:"Pacific Fabrication Co.",
    email:"l.chen@pacificfab.com", phone:"(503) 555-0292",
    address:"7200 NE Columbia Blvd", city:"Portland", state:"OR", zip:"97218",
    website:"pacificfab.com", linkedin:"linkedin.com/in/lisachen-cfo",
    vertical:"manufacturing", source:"Industry Association — PMA", stage:"Active Client", status:"Active",
    score:89, tags:["VIP","Enterprise","Contract Renewal Q4"],
    lifetimeValue:312000, dealCount:4, quoteCount:5, avgDealSize:78000,
    lastContact:"Jun 2, 2026", firstContact:"Apr 17, 2024", lastPurchase:"May 1, 2026",
    nextAction:"Q4 contract renewal — initiate 90 days before expiry", buyProbability:82,
    preferredChannel:"Email + Quarterly Review", responseTime:"Same business day",
    emailsOpened:38, emailsSent:42, meetingsHeld:12, quotesAccepted:4, quotesSent:5,
    pageVisits:198, lastPageVisited:"Contract management dashboard", referralSource:"PMA Annual Conference",
    notes:"Numbers-driven. Wants cost reduction data upfront. Schedule quarterly business reviews.",
  },
  {
    id:9, firstName:"James", lastName:"Whitfield", fn:"James", ln:"Whitfield",
    name:"James Whitfield", title:"Procurement Manager", company:"Apex Composite Materials",
    email:"j.whitfield@apexcomposites.com", phone:"(860) 555-0176",
    address:"300 Griffin Rd", city:"Hartford", state:"CT", zip:"06101",
    website:"apexcomposites.com", linkedin:"linkedin.com/in/jameswhitfield-procurement",
    vertical:"manufacturing", source:"Aerospace Supplier Network", stage:"Estimating", status:"Active",
    score:69, tags:["Defense Subcontractor","Compliance-Heavy","Long Cycle"],
    lifetimeValue:54000, dealCount:1, quoteCount:2, avgDealSize:54000,
    lastContact:"May 16, 2026", firstContact:"Jan 29, 2026", lastPurchase:"",
    nextAction:"Submit revised compliance documentation — ITAR forms outstanding", buyProbability:48,
    preferredChannel:"Email", responseTime:"5–7 business days",
    emailsOpened:7, emailsSent:14, meetingsHeld:3, quotesAccepted:1, quotesSent:2,
    pageVisits:32, lastPageVisited:"Manufacturing vertical compliance", referralSource:"Aerospace Supplier Network Directory",
    notes:"Heavily regulated. Every document needs to go through their compliance team. Patient approach required.",
  },
  // CONSTRUCTION
  {
    id:10, firstName:"Marcus", lastName:"Rodriguez", fn:"Marcus", ln:"Rodriguez",
    name:"Marcus Rodriguez", title:"Owner", company:"Storm Shield Roofing & Restoration",
    email:"marcus@stormshieldroofing.com", phone:"(813) 555-0422",
    address:"1840 E Hillsborough Ave", city:"Tampa", state:"FL", zip:"33610",
    website:"stormshieldroofing.com", linkedin:"linkedin.com/in/marcusrodriguez-roofing",
    vertical:"construction", source:"Facebook Ads — Storm Season", stage:"Active Client", status:"Active",
    score:85, tags:["Owner-Operator","High Volume","Insurance Work"],
    lifetimeValue:42800, dealCount:5, quoteCount:8, avgDealSize:8560,
    lastContact:"Jun 3, 2026", firstContact:"Aug 15, 2025", lastPurchase:"May 28, 2026",
    nextAction:"Send 3-job estimate package for June storm damage leads", buyProbability:78,
    preferredChannel:"Text", responseTime:"< 30 minutes",
    emailsOpened:18, emailsSent:26, meetingsHeld:4, quotesAccepted:5, quotesSent:8,
    pageVisits:134, lastPageVisited:"Quote builder", referralSource:"Facebook Ads — storm restoration",
    notes:"Moves fast. Has 6-8 active jobs at any time. Wants quoting to be 10 minutes or less.",
  },
  {
    id:11, firstName:"Jennifer", lastName:"Walsh", fn:"Jennifer", ln:"Walsh",
    name:"Jennifer Walsh", title:"Office Manager", company:"Storm Shield Roofing & Restoration",
    email:"j.walsh@stormshieldroofing.com", phone:"(813) 555-0423",
    address:"1840 E Hillsborough Ave", city:"Tampa", state:"FL", zip:"33610",
    website:"stormshieldroofing.com", linkedin:"",
    vertical:"construction", source:"Inbound — Referral from Marcus", stage:"Active Client", status:"Active",
    score:72, tags:["Office Contact","Admin","Secondary Decision Maker"],
    lifetimeValue:0, dealCount:0, quoteCount:0, avgDealSize:0,
    lastContact:"May 30, 2026", firstContact:"Sep 2, 2025", lastPurchase:"",
    nextAction:"Confirm scheduling for 3 upcoming jobs next week", buyProbability:0,
    preferredChannel:"Email", responseTime:"Same day",
    emailsOpened:24, emailsSent:28, meetingsHeld:1, quotesAccepted:0, quotesSent:0,
    pageVisits:56, lastPageVisited:"Document center", referralSource:"Introduced by Marcus Rodriguez",
    notes:"Runs day-to-day operations. Gate-keeper for Marcus. Keep her informed and she'll champion internally.",
  },
  {
    id:12, firstName:"Derek", lastName:"Mills", fn:"Derek", ln:"Mills",
    name:"Derek Mills", title:"Owner", company:"Gulf Coast HVAC Solutions",
    email:"derek@gulfcoasthvac.com", phone:"(727) 555-0387",
    address:"5500 Park Blvd N", city:"Pinellas Park", state:"FL", zip:"33781",
    website:"gulfcoasthvac.com", linkedin:"linkedin.com/in/derekmills-hvac",
    vertical:"construction", source:"Google Maps — HVAC search", stage:"Active Client", status:"Active",
    score:80, tags:["Service Agreements","Recurring Revenue","Growth Mode"],
    lifetimeValue:31600, dealCount:4, quoteCount:6, avgDealSize:7900,
    lastContact:"Jun 1, 2026", firstContact:"Nov 22, 2025", lastPurchase:"May 12, 2026",
    nextAction:"Upsell to annual service agreement portfolio — 40 residential clients ready", buyProbability:74,
    preferredChannel:"Phone", responseTime:"< 1 hour",
    emailsOpened:21, emailsSent:27, meetingsHeld:5, quotesAccepted:4, quotesSent:6,
    pageVisits:112, lastPageVisited:"Service agreement templates", referralSource:"Google Maps organic",
    notes:"Wants to move from one-off jobs to recurring service contracts. This is the platform to make it happen.",
  },
  {
    id:13, firstName:"Tanya", lastName:"Brooks", fn:"Tanya", ln:"Brooks",
    name:"Tanya Brooks", title:"Service Coordinator", company:"Gulf Coast HVAC Solutions",
    email:"t.brooks@gulfcoasthvac.com", phone:"(727) 555-0388",
    address:"5500 Park Blvd N", city:"Pinellas Park", state:"FL", zip:"33781",
    website:"gulfcoasthvac.com", linkedin:"",
    vertical:"construction", source:"Introduced by Derek Mills", stage:"Active Client", status:"Active",
    score:61, tags:["Coordinator","Scheduling","Operational Contact"],
    lifetimeValue:0, dealCount:0, quoteCount:0, avgDealSize:0,
    lastContact:"May 28, 2026", firstContact:"Dec 4, 2025", lastPurchase:"",
    nextAction:"Train on document center for invoice generation", buyProbability:0,
    preferredChannel:"Email", responseTime:"Same day",
    emailsOpened:18, emailsSent:20, meetingsHeld:2, quotesAccepted:0, quotesSent:0,
    pageVisits:44, lastPageVisited:"Invoice templates", referralSource:"Internal — Derek Mills",
    notes:"Handles all scheduling and dispatching. Will be daily user of CRM once fully onboarded.",
  },
  {
    id:14, firstName:"Kevin", lastName:"Patel", fn:"Kevin", ln:"Patel",
    name:"Kevin Patel", title:"Owner", company:"Precision Plumbing + Electric",
    email:"kevin@precisionpe.com", phone:"(727) 555-0300",
    address:"2210 38th Ave N", city:"St. Petersburg", state:"FL", zip:"33713",
    website:"precisionplumbingelectric.com", linkedin:"linkedin.com/in/kevinpatel-trades",
    vertical:"construction", source:"Nextdoor — Organic Referral", stage:"Discovery", status:"Active",
    score:66, tags:["Small Shop","High Growth","Quoting Pain Point"],
    lifetimeValue:14200, dealCount:3, quoteCount:5, avgDealSize:4733,
    lastContact:"May 20, 2026", firstContact:"Mar 1, 2026", lastPurchase:"Apr 30, 2026",
    nextAction:"Demo the agent-guided quote builder — he manually builds every quote now", buyProbability:62,
    preferredChannel:"Text", responseTime:"< 2 hours",
    emailsOpened:12, emailsSent:18, meetingsHeld:3, quotesAccepted:3, quotesSent:5,
    pageVisits:74, lastPageVisited:"Quoting agent demo", referralSource:"Nextdoor platform organic",
    notes:"Spends 45+ minutes building each quote manually. Agent quoting would save hours per week.",
  },
  // PROFESSIONAL SERVICES
  {
    id:15, firstName:"Amanda", lastName:"Chen", fn:"Amanda", ln:"Chen",
    name:"Amanda Chen", title:"Managing Partner", company:"Meridian Law Group",
    email:"a.chen@meridianlaw.com", phone:"(813) 555-0514",
    address:"101 E Kennedy Blvd, Suite 1800", city:"Tampa", state:"FL", zip:"33602",
    website:"meridianlaw.com", linkedin:"linkedin.com/in/amandachen-esq",
    vertical:"professional_services", source:"Tampa Bay Chamber Referral", stage:"Active Client", status:"Active",
    score:88, tags:["Partner Level","High LTV","Referral Driver"],
    lifetimeValue:64000, dealCount:2, quoteCount:3, avgDealSize:32000,
    lastContact:"Jun 2, 2026", firstContact:"Jun 12, 2025", lastPurchase:"May 1, 2026",
    nextAction:"Introduce Echo email nurture sequence for prospective business clients", buyProbability:76,
    preferredChannel:"Email", responseTime:"Same business day",
    emailsOpened:31, emailsSent:36, meetingsHeld:7, quotesAccepted:2, quotesSent:3,
    pageVisits:144, lastPageVisited:"Professional services templates", referralSource:"Tampa Bay Chamber of Commerce",
    notes:"Business development focused. Wants to build systematic referral pipeline. Compliance-aware.",
  },
  {
    id:16, firstName:"Robert", lastName:"Vasquez", fn:"Robert", ln:"Vasquez",
    name:"Robert Vasquez", title:"Senior Partner — Real Estate Law", company:"Meridian Law Group",
    email:"r.vasquez@meridianlaw.com", phone:"(813) 555-0516",
    address:"101 E Kennedy Blvd, Suite 1800", city:"Tampa", state:"FL", zip:"33602",
    website:"meridianlaw.com", linkedin:"linkedin.com/in/robertvasquez-law",
    vertical:"professional_services", source:"Amanda Chen — Internal Referral", stage:"Warm Lead", status:"Active",
    score:59, tags:["Secondary Contact","Real Estate Specialty","Cross-Sell"],
    lifetimeValue:0, dealCount:0, quoteCount:1, avgDealSize:0,
    lastContact:"May 14, 2026", firstContact:"Jan 8, 2026", lastPurchase:"",
    nextAction:"Follow up on real estate law service package proposal", buyProbability:38,
    preferredChannel:"Email", responseTime:"2–3 days",
    emailsOpened:8, emailsSent:14, meetingsHeld:2, quotesAccepted:0, quotesSent:1,
    pageVisits:28, lastPageVisited:"Real estate professional templates", referralSource:"Amanda Chen referral",
    notes:"Skeptical of technology tools. Needs to see a clear time-savings case. Amanda is the champion.",
  },
  {
    id:17, firstName:"Patricia", lastName:"Okafor", fn:"Patricia", ln:"Okafor",
    name:"Patricia Okafor", title:"Founding Advisor", company:"Atlas Wealth Advisors",
    email:"p.okafor@atlaswealthadvisors.com", phone:"(727) 555-0632",
    address:"360 Central Ave, Suite 1600", city:"St. Petersburg", state:"FL", zip:"33701",
    website:"atlaswealthadvisors.com", linkedin:"linkedin.com/in/patriciaokafor-cfa",
    vertical:"professional_services", source:"Wealth Management Conference 2025", stage:"Active Client", status:"Active",
    score:91, tags:["Founder","High LTV","Compliance-Sensitive"],
    lifetimeValue:96400, dealCount:3, quoteCount:4, avgDealSize:32133,
    lastContact:"Jun 3, 2026", firstContact:"May 5, 2025", lastPurchase:"Apr 18, 2026",
    nextAction:"Quarterly business review — new client onboarding workflow proposal ready", buyProbability:84,
    preferredChannel:"Video Call", responseTime:"< 4 hours",
    emailsOpened:36, emailsSent:40, meetingsHeld:10, quotesAccepted:3, quotesSent:4,
    pageVisits:192, lastPageVisited:"Engagement letter templates", referralSource:"WMC Annual Conference 2025",
    notes:"Very detail-oriented. Has compliance officer review all vendor agreements. High LTV once in.",
  },
  {
    id:18, firstName:"James", lastName:"Thornton", fn:"James", ln:"Thornton",
    name:"James Thornton", title:"Principal CPA", company:"Summit CPA & Advisory",
    email:"j.thornton@summitcpa.com", phone:"(813) 555-0579",
    address:"4830 W Kennedy Blvd, Suite 600", city:"Tampa", state:"FL", zip:"33609",
    website:"summitcpa.com", linkedin:"linkedin.com/in/jamesthornton-cpa",
    vertical:"professional_services", source:"Referral — Patricia Okafor", stage:"Proposal Sent", status:"Active",
    score:77, tags:["CPA","Small Business Focused","Warm Referral"],
    lifetimeValue:18600, dealCount:2, quoteCount:3, avgDealSize:9300,
    lastContact:"May 26, 2026", firstContact:"Mar 3, 2026", lastPurchase:"Apr 2, 2026",
    nextAction:"Follow up on Q3 growth advisory proposal — 7 days no response", buyProbability:65,
    preferredChannel:"Email", responseTime:"24 hours",
    emailsOpened:19, emailsSent:24, meetingsHeld:4, quotesAccepted:2, quotesSent:3,
    pageVisits:86, lastPageVisited:"Advisory services quote template", referralSource:"Patricia Okafor referral",
    notes:"Practical and numbers-focused. Wants to understand ROI before any commitment. Strong referral potential.",
  },
  {
    id:19, firstName:"Nicole", lastName:"Bradford", fn:"Nicole", ln:"Bradford",
    name:"Nicole Bradford", title:"Client Relations Manager", company:"Summit CPA & Advisory",
    email:"n.bradford@summitcpa.com", phone:"(813) 555-0580",
    address:"4830 W Kennedy Blvd, Suite 600", city:"Tampa", state:"FL", zip:"33609",
    website:"summitcpa.com", linkedin:"linkedin.com/in/nicolebradford",
    vertical:"professional_services", source:"Introduced by James Thornton", stage:"Active Client", status:"Active",
    score:68, tags:["Coordinator","Daily User","Onboarding"],
    lifetimeValue:0, dealCount:0, quoteCount:0, avgDealSize:0,
    lastContact:"May 30, 2026", firstContact:"Mar 10, 2026", lastPurchase:"",
    nextAction:"Complete CRM onboarding — still has 12 contacts to import", buyProbability:0,
    preferredChannel:"Email", responseTime:"Same day",
    emailsOpened:22, emailsSent:25, meetingsHeld:3, quotesAccepted:0, quotesSent:0,
    pageVisits:68, lastPageVisited:"Contact import guide", referralSource:"James Thornton internal",
    notes:"Will be the heaviest CRM user day-to-day. Enthusiastic adopter. Help her succeed and James stays.",
  },
];

// ── DEALS ────────────────────────────────────────────────────────────────────
export const ALL_DEALS: any[] = [
  // Real Estate
  {id:"d1",  contactId:1,  company:"Apex Realty Group",        title:"Hialeah Listing Staging Package",   value:8180,   stage:"Closed Won",       probability:100, closeDate:"Jun 2, 2026",  vertical:"real_estate"},
  {id:"d2",  contactId:1,  company:"Apex Realty Group",        title:"Coral Gables Staging — 4BR Home",   value:12400,  stage:"Proposal Sent",    probability:65,  closeDate:"Jun 20, 2026", vertical:"real_estate"},
  {id:"d3",  contactId:1,  company:"Apex Realty Group",        title:"Q3 Volume Staging Agreement",       value:24000,  stage:"Discovery",        probability:30,  closeDate:"Jul 15, 2026", vertical:"real_estate"},
  {id:"d4",  contactId:2,  company:"Suncoast Properties",      title:"Ybor City Duplex Photography",      value:3200,   stage:"Closed Won",       probability:100, closeDate:"May 28, 2026", vertical:"real_estate"},
  {id:"d5",  contactId:2,  company:"Suncoast Properties",      title:"South Tampa Listing Bundle — 3 Properties", value:18600, stage:"Contract Signed",probability:90, closeDate:"Jun 10, 2026", vertical:"real_estate"},
  // Healthcare
  {id:"d6",  contactId:4,  company:"Okafor Family Medicine",   title:"Patient Acquisition Campaign — Q2", value:14800,  stage:"Active Patient",   probability:80,  closeDate:"Jul 1, 2026",  vertical:"healthcare"},
  {id:"d7",  contactId:5,  company:"Sunrise Dental Group",     title:"6-Location Marketing Retainer",     value:84000,  stage:"Active Client",    probability:95,  closeDate:"Jun 30, 2026", vertical:"healthcare"},
  {id:"d8",  contactId:5,  company:"Sunrise Dental Group",     title:"New Patient Funnel — Locations 4-6",value:42000,  stage:"Proposal Sent",    probability:70,  closeDate:"Jul 15, 2026", vertical:"healthcare"},
  // Manufacturing
  {id:"d9",  contactId:7,  company:"Harmon Industrial Supply", title:"12-Month Platform License",         value:96000,  stage:"Negotiation",      probability:58,  closeDate:"Jul 31, 2026", vertical:"manufacturing"},
  {id:"d10", contactId:8,  company:"Pacific Fabrication Co.",  title:"Annual Enterprise Contract — Renewal",value:142000,stage:"Active Client",   probability:90,  closeDate:"Dec 31, 2026", vertical:"manufacturing"},
  {id:"d11", contactId:9,  company:"Apex Composite Materials", title:"Defense Program Pilot — 6 Month",   value:54000,  stage:"Estimating",       probability:45,  closeDate:"Aug 1, 2026",  vertical:"manufacturing"},
  // Construction
  {id:"d12", contactId:10, company:"Storm Shield Roofing",     title:"Roof Replacement — Thompson Residence",value:11200,stage:"Closed Won",      probability:100, closeDate:"May 30, 2026", vertical:"construction"},
  {id:"d13", contactId:10, company:"Storm Shield Roofing",     title:"Insurance Claim Package — Oak Hill Estates",value:28400,stage:"Contract Signed",probability:90,closeDate:"Jun 14, 2026",vertical:"construction"},
  {id:"d14", contactId:12, company:"Gulf Coast HVAC Solutions","title":"Annual Service Agreement — 38 Units",value:22800,stage:"Proposal Sent",   probability:70,  closeDate:"Jun 25, 2026", vertical:"construction"},
  {id:"d15", contactId:14, company:"Precision Plumbing",       title:"Bathroom Reno — Northshore Condos",  value:6400,   stage:"Estimate Sent",    probability:55,  closeDate:"Jul 5, 2026",  vertical:"construction"},
  // Professional Services
  {id:"d16", contactId:15, company:"Meridian Law Group",       title:"Business Dev + Client Acquisition",  value:36000,  stage:"Active Client",    probability:90,  closeDate:"Jun 30, 2026", vertical:"professional_services"},
  {id:"d17", contactId:17, company:"Atlas Wealth Advisors",    title:"New Client Onboarding Automation",   value:42000,  stage:"Active Client",    probability:88,  closeDate:"Jun 30, 2026", vertical:"professional_services"},
  {id:"d18", contactId:18, company:"Summit CPA & Advisory",    title:"Q3 Growth Advisory Package",         value:12400,  stage:"Proposal Sent",    probability:62,  closeDate:"Jul 1, 2026",  vertical:"professional_services"},
];

export const ALL_STAGES = [
  "New Lead","Qualify","Outreach","Engaged","Meeting Set",
  "Proposal Sent","Negotiation","Closed Won","Retention"
];

export const PIPELINE_STAGES = ALL_STAGES;

export const ACTIVITIES: any[] = [
  {id:"act1", contactId:1,  type:"email",   date:"Jun 2, 2026",   title:"Re: Hialeah staging confirmed",          body:"Sarah confirmed she wants to move forward with the full staging package.",  status:"replied"},
  {id:"act2", contactId:1,  type:"quote",   date:"May 30, 2026",  title:"Quote sent — Hialeah staging Q-2026-001", body:"$8,180 — staging, photography, landscaping. Accepted same day.",           status:"accepted"},
  {id:"act3", contactId:2,  type:"meeting", date:"Jun 3, 2026",   title:"Listing pipeline review — 45 min",        body:"Reviewed 4 upcoming listings. All need staging and photography.",           status:"completed"},
  {id:"act4", contactId:5,  type:"call",    date:"Jun 1, 2026",   title:"Expansion planning call — Locations 4-6", body:"Marcus confirmed budget approved for 3 new locations. Proposal requested.", status:"completed"},
  {id:"act5", contactId:10, type:"sms",     date:"Jun 3, 2026",   title:"Follow up on Oak Hill Estates contract",  body:"Contract signed. Insurance adjuster report attached. Job starts June 14.", status:"delivered"},
  {id:"act6", contactId:12, type:"email",   date:"Jun 1, 2026",   title:"Service agreement proposal sent",         body:"38-unit annual HVAC service agreement. $600/unit. Auto-renewal.",           status:"sent"},
  {id:"act7", contactId:15, type:"meeting", date:"May 28, 2026",  title:"Quarterly business review — Meridian",    body:"Reviewed Q1 results. 3 new client referrals confirmed for Q2.",             status:"completed"},
  {id:"act8", contactId:17, type:"email",   date:"Jun 2, 2026",   title:"Onboarding workflow proposal",            body:"Patricia reviewed the proposal. Compliance team has 2 questions.",          status:"viewed"},
];

// Legacy field aliases for CRM compatibility
export const DEALS_BY_STAGE = ALL_DEALS.reduce((acc: any, d: any) => {
  if (!acc[d.stage]) acc[d.stage] = [];
  acc[d.stage].push({ ...d, val: d.value, co: d.company, prob: d.probability, close: d.closeDate,
    stage_hist: [d.stage], contact: d.title.split("—")[0]?.trim() || "" });
  return acc;
}, {});
