import type { Contact, Company, Deal, Activity } from "./types";

export const VERTICAL_CONFIG: Record<string, { label: string; icon: string; emoji: string; color: string; accent: string; signals: string[] }> = {
  real_estate: {
    label: "Real Estate", icon: "Home", emoji: "🏠", color: "#00C896", accent: "#007A5C",
    signals: ["Distress Index","Equity Score","Sellability","Days Vacant","Tax Delinquency"],
  },
  healthcare: {
    label: "Healthcare", icon: "HeartPulse", emoji: "🏥", color: "#3B9EFF", accent: "#1D4ED8",
    signals: ["Practice Growth","Referral Volume","Payer Mix Score","Compliance Risk","Expansion Signal"],
  },
  manufacturing: {
    label: "Manufacturing", icon: "Factory", emoji: "🏭", color: "#F59E0B", accent: "#B45309",
    signals: ["Procurement Signal","Financial Health","Growth Velocity","Supply Chain Risk","Equipment Need"],
  },
};

export const ALL_VERTICALS = Object.entries(VERTICAL_CONFIG).map(([id, v]) => ({ id, ...v }));

// ── CONTACTS ──────────────────────────────────────────────────────────────────
export const CONTACTS: Contact[] = [

  // ── REAL ESTATE ──────────────────────────────────────────────────────────
  { id:1,  vertical:"real_estate", fn:"Sarah",  ln:"Mitchell",  co:"Apex Realty Group",       role:"Managing Broker",      email:"s.mitchell@apexrealty.com",     phone:"(305) 714-2381", status:"customer",  score:88, city:"Miami, FL",        deals:3, lastAct:"Jun 4 · 2:18 PM",   notes:"Expanding to Broward Q3 — could add 3–5 listings/quarter. 4 closed deals since March 2024.", breakdown:[{n:"Distress Index",s:92},{n:"Equity Score",s:88},{n:"Sellability",s:85},{n:"Days Vacant",s:78},{n:"Tax Delinquency",s:90}], insight:"Portfolio shows 3 active listings with high distress signals and significant equity. One Hialeah property closed in under 14 days — fastest in vertical. Broward expansion confirmed.", action:"Send Q3 volume pricing proposal before July 1 — expansion timing is now." },
  { id:2,  vertical:"real_estate", fn:"James",  ln:"Thornton",  co:"Suncoast Properties",     role:"Broker/Owner",          email:"j.thornton@suncoastproperties.com", phone:"(813) 492-0817", status:"customer",  score:94, city:"Tampa, FL",        deals:4, lastAct:"Jun 3 · 4:45 PM",   notes:"40+ active listings. Manages 5 agents. Sent 2 referrals our way this quarter. Top account.", breakdown:[{n:"Distress Index",s:95},{n:"Equity Score",s:94},{n:"Sellability",s:92},{n:"Days Vacant",s:88},{n:"Tax Delinquency",s:96}], insight:"Top-tier client. REO Portfolio — Broward closed May 30 at $178K. All score dimensions 88–96. 5th deal this year.", action:"Monthly check-in and market briefing. First look at any off-market distressed pipeline." },
  { id:3,  vertical:"real_estate", fn:"Maria",  ln:"Delgado",   co:"Blue Horizon Homes",      role:"Listing Agent",         email:"m.delgado@bluehorizonhomes.com",  phone:"(786) 553-0902", status:"contacted", score:72, city:"Miami, FL",        deals:1, lastAct:"May 31 · 5:30 PM",  notes:"Requested AI scoring demo — schedule Zoom Friday 2pm. 18 active listings in Miami-Dade.", breakdown:[{n:"Distress Index",s:68},{n:"Equity Score",s:75},{n:"Sellability",s:72},{n:"Days Vacant",s:65},{n:"Tax Delinquency",s:80}], insight:"Mid-range portfolio with moderate equity signals. One property showing early vacancy signs at 45 days. Demo request is a strong intent signal.", action:"Run live AI scoring demo on her top 3 listings. Show distress + equity overlay." },
  { id:4,  vertical:"real_estate", fn:"Robert", ln:"Chen",      co:"Palmetto Real Estate",    role:"Investment Buyer",      email:"r.chen@palmettore.com",           phone:"(904) 338-1247", status:"new",       score:61, city:"Jacksonville, FL", deals:0, lastAct:"May 26 · 2:00 PM",  notes:"Referred by James Thornton. Targets distressed SFR in Jacksonville and Duval County.", breakdown:[{n:"Distress Index",s:58},{n:"Equity Score",s:64},{n:"Sellability",s:60},{n:"Days Vacant",s:55},{n:"Tax Delinquency",s:68}], insight:"New referral with limited data history. Referral quality from Thornton is high. Focus is SFR acquisition — different profile from existing accounts.", action:"Intro call — qualify investment criteria, deal cadence, and current data stack." },
  { id:5,  vertical:"real_estate", fn:"Angela", ln:"Brooks",    co:"Keys & Coast Realty",     role:"Property Manager",      email:"a.brooks@keyscoastrealty.com",    phone:"(305) 619-4720", status:"qualified", score:81, city:"Key West, FL",     deals:2, lastAct:"Jun 1 · 10:15 AM",  notes:"Manages 62 vacation rental units. Management contract proposal sent — $84K ARR.", breakdown:[{n:"Distress Index",s:80},{n:"Equity Score",s:83},{n:"Sellability",s:79},{n:"Days Vacant",s:78},{n:"Tax Delinquency",s:85}], insight:"Solid vacation rental portfolio with high seasonal occupancy. Two new units coming to market next month. Annual contract is a strong recurring revenue opportunity.", action:"Follow up on management contract. Close before July peak season lockout." },
  { id:6,  vertical:"real_estate", fn:"Priya",  ln:"Sharma",    co:"Clearwater Investments",  role:"Portfolio Manager",     email:"p.sharma@clearwaterinv.com",      phone:"(727) 481-0063", status:"customer",  score:91, city:"Clearwater, FL",   deals:3, lastAct:"Jun 1 · 3:00 PM",   notes:"Buys 2–3 distressed properties per quarter. $520K off-market package proposal sent.", breakdown:[{n:"Distress Index",s:94},{n:"Equity Score",s:91},{n:"Sellability",s:90},{n:"Days Vacant",s:85},{n:"Tax Delinquency",s:93}], insight:"Premium distressed-asset buyer with consistent deal cadence. UCC filings and county records confirm 3 acquisitions in 90 days. Portfolio growing.", action:"Priority account — first look at all new distressed inventory. Close $520K package by Aug 5." },

  // ── HEALTHCARE ────────────────────────────────────────────────────────────
  { id:10, vertical:"healthcare",  fn:"Dr. Linda", ln:"Okafor",    co:"Okafor Family Medicine",   role:"Practice Owner",        email:"l.okafor@okaformd.com",          phone:"(312) 847-2194", status:"qualified", score:87, city:"Chicago, IL",      deals:2, lastAct:"Jun 4 · 1:00 PM",   notes:"Second location filing confirmed with IL state. Demo rescheduled for Friday 1pm. Expansion in 90 days.", breakdown:[{n:"Practice Growth",s:91},{n:"Referral Volume",s:88},{n:"Payer Mix Score",s:84},{n:"Compliance Risk",s:76},{n:"Expansion Signal",s:95}], insight:"High expansion signal — second location state filing confirmed June 2. Referral volume up 34% YOY. 8 providers, strong private-pay mix. Enterprise package is a natural fit.", action:"Demo this Friday — bring expansion ROI case study. Timeline is tight." },
  { id:11, vertical:"healthcare",  fn:"Marcus",    ln:"Jimenez",   co:"Sunrise Dental Group",     role:"Managing Partner",      email:"m.jimenez@sunrisedental.com",    phone:"(469) 381-0592", status:"customer",  score:93, city:"Dallas, TX",       deals:3, lastAct:"Jun 3 · 2:00 PM",   notes:"6-location dental group, DFW market. Enterprise proposal at $185K sent. CFO reviewing.", breakdown:[{n:"Practice Growth",s:95},{n:"Referral Volume",s:92},{n:"Payer Mix Score",s:90},{n:"Compliance Risk",s:88},{n:"Expansion Signal",s:97}], insight:"Multi-location dental group, 42 total staff. Payer mix 72% private insurance. Minimal compliance exposure. 3 additional locations planned in 2027 — strong expansion signal.", action:"Upsell to Enterprise Suite — forward to CFO. Decision expected Aug 10." },
  { id:12, vertical:"healthcare",  fn:"Aisha",     ln:"Thompson",  co:"Coastal Behavioral Health", role:"Clinical Director",     email:"a.thompson@coastalbh.com",       phone:"(813) 527-0338", status:"contacted", score:74, city:"Tampa, FL",        deals:1, lastAct:"Jun 1 · 4:00 PM",   notes:"Behavioral health telehealth billing compliance risk flagged. Case study sent for follow-up.", breakdown:[{n:"Practice Growth",s:78},{n:"Referral Volume",s:72},{n:"Payer Mix Score",s:68},{n:"Compliance Risk",s:65},{n:"Expansion Signal",s:80}], insight:"Behavioral health is the fastest growing post-pandemic specialty. Telehealth billing audit flagged moderate compliance risk — compliance module is a strong entry point.", action:"Send behavioral health ROI case study. Follow up Friday. Compliance angle is the hook." },
  { id:13, vertical:"healthcare",  fn:"Dr. Kevin", ln:"Park",      co:"Park Orthopedic Clinic",   role:"Physician Owner",       email:"k.park@parkorthopedic.com",      phone:"(615) 294-0741", status:"new",       score:65, city:"Nashville, TN",    deals:0, lastAct:"May 24 · 9:30 AM",  notes:"New inbound — orthopedic specialty. IT budget and current vendor pain points not yet qualified.", breakdown:[{n:"Practice Growth",s:62},{n:"Referral Volume",s:68},{n:"Payer Mix Score",s:70},{n:"Compliance Risk",s:55},{n:"Expansion Signal",s:60}], insight:"Orthopedic clinic with steady referral volume. Payer mix skews Medicare/Medicaid — watch revenue cycle. IT budget and vendor status not yet known. Intro email delivered.", action:"Intro call — qualify IT budget, current EMR vendor, and primary pain point." },
  { id:14, vertical:"healthcare",  fn:"Dr. Rachel",ln:"Torres",    co:"Torres Women's Health",    role:"OB-GYN Practice Owner", email:"r.torres@torreswomenshealth.com", phone:"(305) 703-1482", status:"qualified", score:82, city:"Miami, FL",        deals:2, lastAct:"May 31 · 10:30 AM",  notes:"Second location confirmed — Doral, FL. Mid-market package proposal at $82K sent.", breakdown:[{n:"Practice Growth",s:86},{n:"Referral Volume",s:84},{n:"Payer Mix Score",s:80},{n:"Compliance Risk",s:72},{n:"Expansion Signal",s:85}], insight:"Women's health is a high-growth vertical. Strong referral network across 4 hospital systems. Q4 expansion to Doral confirmed. Mid-market package is well-scoped for her size.", action:"Propose mid-market package — follow up on $82K proposal. Q4 expansion creates urgency." },

  // ── MANUFACTURING ─────────────────────────────────────────────────────────
  { id:20, vertical:"manufacturing", fn:"Greg",    ln:"Harmon",    co:"Harmon Industrial Supply", role:"VP Procurement",        email:"g.harmon@harmonindustrial.com",  phone:"(216) 482-0913", status:"qualified", score:89, city:"Cleveland, OH",    deals:2, lastAct:"Jun 4 · 9:30 AM",   notes:"Q3 budget $2.1M confirmed. CNC + conveyor RFQ expected this week. First closed deal onboarding.", breakdown:[{n:"Procurement Signal",s:94},{n:"Financial Health",s:88},{n:"Growth Velocity",s:85},{n:"Supply Chain Risk",s:78},{n:"Equipment Need",s:92}], insight:"UCC filings show $2.1M equipment financing in last 90 days. Job postings for CNC operators up 40%. Supply Chain Module closed at $94K — now in onboarding. Q3 RFQ is next.", action:"Submit equipment procurement proposal this week — budget cycle closes Jul 31." },
  { id:21, vertical:"manufacturing", fn:"Sandra",  ln:"Wu",        co:"Pacific Fabrication Co",   role:"Operations Director",   email:"s.wu@pacificfab.com",            phone:"(503) 246-1837", status:"customer",  score:95, city:"Portland, OR",     deals:4, lastAct:"Jun 3 · 3:30 PM",   notes:"$6.4M procurement processed through KOVA in Q2. Enterprise renewal at $620K sent. CFO review.", breakdown:[{n:"Procurement Signal",s:96},{n:"Financial Health",s:95},{n:"Growth Velocity",s:93},{n:"Supply Chain Risk",s:88},{n:"Equipment Need",s:97}], insight:"Top-tier account. $24.8M annual revenue, 18% YOY growth per SEC filing. Supply chain diversified across 4 regions. 3 additional plant locations flagged for next contract cycle.", action:"Renew enterprise contract — $620K proposal with CFO. Decision deadline Aug 1." },
  { id:22, vertical:"manufacturing", fn:"Derek",   ln:"Coleman",   co:"Midwest Steel Solutions",  role:"Plant Manager",         email:"d.coleman@midweststeel.com",     phone:"(317) 558-0246", status:"contacted", score:71, city:"Indianapolis, IN", deals:1, lastAct:"May 31 · 11:00 AM",  notes:"OSHA inspection flagged 2 aging press units. Forced equipment replacement cycle likely Q1 next year.", breakdown:[{n:"Procurement Signal",s:68},{n:"Financial Health",s:74},{n:"Growth Velocity",s:70},{n:"Supply Chain Risk",s:65},{n:"Equipment Need",s:75}], insight:"Moderate growth signals. OSHA inspection found aging equipment — Equipment Need score rose to 75 this week. Likely forced replacement in 6–12 months creates natural entry point.", action:"Nurture now with Q4 manufacturing outlook. Revisit Q1 when replacement cycle opens." },
  { id:23, vertical:"manufacturing", fn:"Tamara",  ln:"Reeves",    co:"Reeves Precision Parts",   role:"CEO",                   email:"t.reeves@reevesprecision.com",   phone:"(423) 601-0384", status:"new",       score:58, city:"Chattanooga, TN",  deals:0, lastAct:"May 24 · 3:00 PM",  notes:"Small precision parts shop. New inbound — government contract filings suggest aerospace subcontracting.", breakdown:[{n:"Procurement Signal",s:55},{n:"Financial Health",s:60},{n:"Growth Velocity",s:56},{n:"Supply Chain Risk",s:52},{n:"Equipment Need",s:62}], insight:"Small-batch precision manufacturer. Government contract filings suggest DoD aerospace subcontract. Limited public data but referral quality is high.", action:"Intro call — qualify production capacity and RFQ volume." },
  { id:24, vertical:"manufacturing", fn:"James",   ln:"Patel",     co:"Apex Composite Materials", role:"Purchasing Director",   email:"j.patel@apexcomposite.com",     phone:"(860) 412-0729", status:"qualified", score:84, city:"Hartford, CT",     deals:1, lastAct:"Jun 1 · 2:00 PM",   notes:"DoD subcontract awarded June 1. Needs supply chain intelligence for 3-country raw material sourcing.", breakdown:[{n:"Procurement Signal",s:88},{n:"Financial Health",s:85},{n:"Growth Velocity",s:82},{n:"Supply Chain Risk",s:78},{n:"Equipment Need",s:86}], insight:"Aerospace composite supplier with active DoD contract. Import records show raw material sourcing from US, Japan, and Germany — supply chain risk exposure is real.", action:"Send supply chain intelligence proposal — $56K is priced right for their risk profile." },
];

// ── COMPANIES ─────────────────────────────────────────────────────────────────
export const COMPANIES: Company[] = [
  { id:1, vertical:"real_estate",   name:"Apex Realty Group",        industry:"Residential Brokerage",  size:"12 agents, 3 admin",    city:"Miami, FL",        contacts:3, deals:4, revenue:"$2.41M",  since:"2021" },
  { id:2, vertical:"real_estate",   name:"Suncoast Properties",      industry:"Full-Service Brokerage", size:"28 agents, 6 support",  city:"Tampa, FL",        contacts:5, deals:7, revenue:"$5.18M",  since:"2019" },
  { id:3, vertical:"real_estate",   name:"Clearwater Investments",   industry:"Investment Portfolio",   size:"4 principals, 2 analysts",city:"Clearwater, FL",  contacts:2, deals:3, revenue:"$12.3M",  since:"2022" },
  { id:4, vertical:"healthcare",    name:"Okafor Family Medicine",   industry:"Primary Care",           size:"8 providers, 14 staff", city:"Chicago, IL",      contacts:2, deals:2, revenue:"$3.24M",  since:"2018" },
  { id:5, vertical:"healthcare",    name:"Sunrise Dental Group",     industry:"Dental — Multi-Location",size:"6 locations, 38 staff", city:"Dallas, TX",       contacts:3, deals:3, revenue:"$8.47M",  since:"2016" },
  { id:6, vertical:"healthcare",    name:"Coastal Behavioral Health",industry:"Behavioral Health",      size:"12 clinicians, 8 support",city:"Tampa, FL",       contacts:2, deals:1, revenue:"$1.92M",  since:"2020" },
  { id:7, vertical:"manufacturing", name:"Harmon Industrial Supply",  industry:"Industrial Distribution", size:"88 employees",         city:"Cleveland, OH",    contacts:2, deals:2, revenue:"$14.2M",  since:"2015" },
  { id:8, vertical:"manufacturing", name:"Pacific Fabrication Co",   industry:"Metal Fabrication",      size:"224 employees",         city:"Portland, OR",     contacts:3, deals:4, revenue:"$24.8M",  since:"2011" },
  { id:9, vertical:"manufacturing", name:"Apex Composite Materials", industry:"Aerospace Composites",   size:"47 employees",          city:"Hartford, CT",     contacts:2, deals:1, revenue:"$6.84M",  since:"2017" },
];

// ── DEALS ─────────────────────────────────────────────────────────────────────
export const ALL_DEALS: Record<string, Record<string, Deal[]>> = {
  real_estate: {
    "New Lead":      [{id:1,title:"3BR Wholesale — Hialeah SFR",co:"Apex Realty Group",val:48000,contact:"Sarah Mitchell",prob:20,close:"Aug 30",stage_hist:["New Lead"]},{id:2,title:"Distressed Duplex — Tampa Heights",co:"Clearwater Investments",val:72000,contact:"Robert Chen",prob:25,close:"Sep 15",stage_hist:["New Lead"]}],
    "Contacted":     [{id:3,title:"Off-Market SFR Portfolio (4 units)",co:"Clearwater Investments",val:215000,contact:"Priya Sharma",prob:40,close:"Sep 1",stage_hist:["New Lead","Contacted"]},{id:4,title:"Brickell Condo Flip",co:"Apex Realty Group",val:38000,contact:"Maria Delgado",prob:35,close:"Sep 20",stage_hist:["New Lead","Contacted"]}],
    "Qualified":     [{id:5,title:"Waterfront Listing — Key West",co:"Keys & Coast Realty",val:145000,contact:"Angela Brooks",prob:60,close:"Aug 22",stage_hist:["New Lead","Contacted","Qualified"]}],
    "Proposal Sent": [{id:7,title:"Annual Property Management — 62-Unit Portfolio",co:"Suncoast Properties",val:84000,contact:"James Thornton",prob:75,close:"Aug 18",stage_hist:["New Lead","Contacted","Qualified","Proposal Sent"]},{id:8,title:"Off-Market Distressed Package × 5",co:"Clearwater Investments",val:520000,contact:"Priya Sharma",prob:80,close:"Aug 5",stage_hist:["New Lead","Contacted","Qualified","Proposal Sent"]}],
    "Closed Won":    [{id:9,title:"REO Portfolio — Broward County",co:"Apex Realty Group",val:178000,contact:"Sarah Mitchell",prob:100,close:"May 30",stage_hist:["New Lead","Contacted","Qualified","Proposal Sent","Closed Won"]}],
  },
  healthcare: {
    "New Lead":      [{id:101,title:"EMR Implementation — Okafor FM",co:"Okafor Family Medicine",val:24000,contact:"Dr. Linda Okafor",prob:25,close:"Sep 10",stage_hist:["New Lead"]},{id:102,title:"Revenue Cycle Optimization — Torres WH",co:"Torres Women's Health",val:18000,contact:"Dr. Rachel Torres",prob:30,close:"Sep 20",stage_hist:["New Lead"]}],
    "Contacted":     [{id:103,title:"Telehealth Compliance Platform — Coastal BH",co:"Coastal Behavioral Health",val:36000,contact:"Aisha Thompson",prob:40,close:"Aug 28",stage_hist:["New Lead","Contacted"]}],
    "Qualified":     [{id:104,title:"Patient Intelligence Suite — Sunrise Dental",co:"Sunrise Dental Group",val:92000,contact:"Marcus Jimenez",prob:65,close:"Aug 15",stage_hist:["New Lead","Contacted","Qualified"]},{id:105,title:"Compliance & Risk Monitor — Park Ortho",co:"Park Orthopedic Clinic",val:28000,contact:"Dr. Kevin Park",prob:55,close:"Sep 1",stage_hist:["New Lead","Contacted","Qualified"]}],
    "Proposal Sent": [{id:106,title:"Enterprise Suite — Sunrise Dental (6 Locations)",co:"Sunrise Dental Group",val:185000,contact:"Marcus Jimenez",prob:80,close:"Aug 10",stage_hist:["New Lead","Contacted","Qualified","Proposal Sent"]}],
    "Closed Won":    [{id:107,title:"Practice Analytics Platform — Okafor FM",co:"Okafor Family Medicine",val:42000,contact:"Dr. Linda Okafor",prob:100,close:"May 28",stage_hist:["New Lead","Contacted","Qualified","Proposal Sent","Closed Won"]}],
  },
  manufacturing: {
    "New Lead":      [{id:201,title:"Q3 Equipment Package — CNC & Conveyor",co:"Harmon Industrial Supply",val:148000,contact:"Greg Harmon",prob:30,close:"Jul 31",stage_hist:["New Lead"]},{id:202,title:"Supply Chain Intelligence — 3-Country Sourcing",co:"Apex Composite Materials",val:56000,contact:"James Patel",prob:25,close:"Sep 15",stage_hist:["New Lead"]}],
    "Contacted":     [{id:203,title:"CNC Press Replacement RFQ — Midwest Steel",co:"Midwest Steel Solutions",val:88000,contact:"Derek Coleman",prob:35,close:"Oct 1",stage_hist:["New Lead","Contacted"]}],
    "Qualified":     [{id:204,title:"Procurement Intelligence Platform — Harmon",co:"Harmon Industrial Supply",val:220000,contact:"Greg Harmon",prob:60,close:"Aug 20",stage_hist:["New Lead","Contacted","Qualified"]},{id:205,title:"Data Intelligence Platform — Pacific Fab",co:"Pacific Fabrication Co",val:380000,contact:"Sandra Wu",prob:70,close:"Aug 5",stage_hist:["New Lead","Contacted","Qualified"]}],
    "Proposal Sent": [{id:206,title:"Enterprise Renewal — Pacific Fab (18-Month)",co:"Pacific Fabrication Co",val:620000,contact:"Sandra Wu",prob:85,close:"Aug 1",stage_hist:["New Lead","Contacted","Qualified","Proposal Sent"]}],
    "Closed Won":    [{id:207,title:"Supply Chain Module — Harmon Industrial",co:"Harmon Industrial Supply",val:94000,contact:"Greg Harmon",prob:100,close:"May 29",stage_hist:["New Lead","Contacted","Qualified","Proposal Sent","Closed Won"]}],
  },
};

export const ALL_STAGES = ["New Lead","Contacted","Qualified","Proposal Sent","Closed Won"];

// ── ACTIVITIES ────────────────────────────────────────────────────────────────
export const ACTIVITIES: Record<string, Activity[]> = {
  real_estate: [
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Sarah Mitchell",  text:"Called — confirmed 3 listings going active in July. Brickell condo, Hialeah SFR, and Key Biscayne TBD. Wants staging quotes by Thursday.", time:"Jun 4 · 2:18 PM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"James Thornton",  text:"Weekly market report delivered. 34% open rate — forwarded to 3 team members within the hour.", time:"Jun 3 · 4:45 PM" },
    { type:"deal",  icon:"TrendingUp",  bg:"#F0FDF4", contact:"Priya Sharma",    text:"Deal advanced to Proposal Sent — Off-Market Distressed Package × 5 ($520K). Decision expected Aug 5.", time:"Jun 2 · 11:30 AM" },
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Priya Sharma",    text:"Called — reviewing 2 new distressed properties in Hialeah. Q3 acquisition budget confirmed at $1.4M.", time:"Jun 1 · 3:00 PM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"Angela Brooks",   text:"Annual management contract proposal sent — 62-unit Keys & Coast portfolio, $84K ARR. Awaiting review.", time:"Jun 1 · 10:15 AM" },
    { type:"note",  icon:"FileText",    bg:"#F8FAFC", contact:"Maria Delgado",   text:"Requested live AI scoring demo for Blue Horizon listings. Schedule Zoom Friday 2pm — strong intent signal.", time:"May 31 · 5:30 PM" },
    { type:"deal",  icon:"TrendingUp",  bg:"#F0FDF4", contact:"James Thornton",  text:"REO Portfolio — Broward County closed at $178K. Suncoast's 5th deal this year. Invoice sent, payment pending.", time:"May 30 · 9:00 AM" },
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Angela Brooks",   text:"Called — 2 new vacation rental units coming to market. Wants photography + 3D walkthrough within 10 days.", time:"May 28 · 4:30 PM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"Robert Chen",     text:"Intro email sent to Palmetto Real Estate — referred by James Thornton. No response yet, follow up Tuesday.", time:"May 27 · 9:00 AM" },
    { type:"note",  icon:"FileText",    bg:"#F8FAFC", contact:"Robert Chen",     text:"New referral from Thornton. Investment buyer, SFR focus in Duval County. Intro call not yet scheduled.", time:"May 26 · 2:00 PM" },
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Sarah Mitchell",  text:"Inbound — Q3 listing inventory update. 3 properties confirmed, 1 more possible in August. Volume pricing discussion flagged.", time:"May 25 · 11:45 AM" },
    { type:"deal",  icon:"TrendingUp",  bg:"#F0FDF4", contact:"James Thornton",  text:"Annual management contract moved to Proposal Sent — $84K ARR. CFO at Suncoast reviewing.",         time:"May 24 · 3:15 PM" },
  ],
  healthcare: [
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Dr. Linda Okafor",  text:"Called — IL state filing for second location confirmed June 2. Demo rescheduled to Friday 1pm. Budget $28K approved.", time:"Jun 4 · 1:00 PM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"Marcus Jimenez",    text:"Enterprise proposal sent — $185K for 6-location Sunrise Dental rollout. Marcus forwarded to CFO.", time:"Jun 3 · 2:00 PM" },
    { type:"deal",  icon:"TrendingUp",  bg:"#F0FDF4", contact:"Marcus Jimenez",    text:"Enterprise Suite advanced to Proposal Sent ($185K). CFO reviewing — decision deadline Aug 10.", time:"Jun 2 · 10:00 AM" },
    { type:"note",  icon:"FileText",    bg:"#F8FAFC", contact:"Aisha Thompson",    text:"Telehealth billing compliance risk flagged in recent audit. Send compliance module case study — this is the right hook.", time:"Jun 1 · 4:00 PM" },
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Dr. Rachel Torres", text:"Called — Q4 expansion on track. Second location in Doral, FL targeting November open. Referral network growing.", time:"May 31 · 10:30 AM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"Aisha Thompson",    text:"Behavioral health ROI case study sent — 3 comparable practices with compliance module. Follow up Friday.", time:"May 30 · 9:15 AM" },
    { type:"deal",  icon:"TrendingUp",  bg:"#F0FDF4", contact:"Dr. Linda Okafor",  text:"Practice Analytics Platform closed at $42K. First closed deal with Okafor FM. Onboarding scheduled for June 10.", time:"May 28 · 3:00 PM" },
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Marcus Jimenez",    text:"Discovery call — 6 DFW locations, 38 staff. Wants full patient analytics + outreach automation. Strong budget signal.", time:"May 27 · 2:30 PM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"Dr. Rachel Torres", text:"Mid-market package proposal sent — $82K. Women's health expansion fit is strong. Awaiting response.", time:"May 26 · 11:00 AM" },
    { type:"note",  icon:"FileText",    bg:"#F8FAFC", contact:"Dr. Kevin Park",    text:"New inbound from orthopedic specialty in Nashville. Needs to qualify IT budget and current vendor before intro call.", time:"May 24 · 9:30 AM" },
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Dr. Linda Okafor",  text:"Discovery call — second location timeline 90 days, IT budget approved at $28K. Referral volume up 34% YOY.", time:"May 22 · 3:45 PM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"Dr. Kevin Park",    text:"Intro email sent to Park Orthopedic. No response yet — follow up Tuesday.", time:"May 21 · 10:00 AM" },
  ],
  manufacturing: [
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Greg Harmon",    text:"Called — Q3 budget $2.1M confirmed. CNC and conveyor RFQ expected by end of week. Budget cycle closes Jul 31.", time:"Jun 4 · 9:30 AM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"Sandra Wu",      text:"Enterprise renewal proposal sent — $620K, 18-month contract. Decision expected by Aug 1. Sandra forwarding to CFO.", time:"Jun 3 · 3:30 PM" },
    { type:"deal",  icon:"TrendingUp",  bg:"#F0FDF4", contact:"Sandra Wu",      text:"Enterprise Renewal advanced to Proposal Sent ($620K). Highest value active deal in pipeline.", time:"Jun 2 · 9:00 AM" },
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"James Patel",   text:"Called — DoD subcontract awarded June 1. Needs 3-country supply chain intelligence module urgently. Proposal requested.", time:"Jun 1 · 2:00 PM" },
    { type:"note",  icon:"FileText",    bg:"#F8FAFC", contact:"Derek Coleman",  text:"OSHA inspection flagged 2 aging press units at Indianapolis plant. Forced replacement cycle likely Q1 2027.", time:"May 31 · 11:00 AM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"James Patel",   text:"Supply chain intelligence proposal sent — $56K. Aerospace composites vertical, strong DoD contract ROI story.", time:"May 30 · 10:00 AM" },
    { type:"deal",  icon:"TrendingUp",  bg:"#F0FDF4", contact:"Greg Harmon",   text:"Supply Chain Module closed at $94K. First closed deal. Onboarding call scheduled for June 6.", time:"May 29 · 4:00 PM" },
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Sandra Wu",     text:"Annual account review — Pacific Fab up 18% YOY. Sandra flagged 3 additional plant locations for next contract cycle.", time:"May 27 · 1:00 PM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"Derek Coleman", text:"Q4 manufacturing outlook report sent. Includes OSHA equipment aging trend data relevant to Midwest Steel.", time:"May 26 · 9:30 AM" },
    { type:"note",  icon:"FileText",    bg:"#F8FAFC", contact:"Tamara Reeves", text:"New inbound — Reeves Precision Parts, Chattanooga. Small shop, but government contract filings show possible DoD aerospace subcontract.", time:"May 24 · 3:00 PM" },
    { type:"call",  icon:"Phone",       bg:"#EFF6FF", contact:"Greg Harmon",   text:"Discovery call — Harmon expanding CNC capacity. Q3 RFQ covers 4 new machines plus conveyor upgrades. Budget approved.", time:"May 22 · 10:15 AM" },
    { type:"email", icon:"Mail",        bg:"#FFFBEB", contact:"Sandra Wu",     text:"Q2 performance report sent. Pacific Fab processed $6.4M in procurement through KOVA this quarter — up 22%.", time:"May 20 · 2:30 PM" },
  ],
};

export const PIPELINE_STAGES = [
  { id:"ingest",    label:"Ingest",      icon:"Inbox",         desc:"Public records + data feeds pulled" },
  { id:"scrub",     label:"Scrub",       icon:"Filter",        desc:"Normalize, dedup, validate" },
  { id:"skiptrace", label:"Skip Trace",  icon:"Search",        desc:"Phone + email resolved" },
  { id:"profile",   label:"Profile",     icon:"Settings2",     desc:"Vertical config applied" },
  { id:"score",     label:"AI Score",    icon:"Brain",         desc:"Claude 0–100 composite score" },
  { id:"listbuild", label:"List Build",  icon:"ClipboardList", desc:"Filter, stack, rank" },
  { id:"outreach",  label:"Outreach",    icon:"Radio",         desc:"AI-personalized SMS/email" },
  { id:"crm",       label:"CRM",         icon:"Users",         desc:"Pipeline + activity tracking" },
  { id:"reports",   label:"Reports",     icon:"Clock",         desc:"Monday AM intelligence briefing" },
];
