export interface DocTemplate {
  id: string; type: "po"|"invoice"|"estimate"|"receipt"|"workorder";
  name: string; industry: string; description: string; accentColor: string;
  defaultTerms: string; defaultNotes: string;
}

export const DOC_TEMPLATES: DocTemplate[] = [
  // ── PURCHASE ORDERS ────────────────────────────────────────────────────────
  { id:"po-general",    type:"po", name:"Standard Goods PO",          industry:"General",            accentColor:"#0F172A", description:"General-purpose purchase order for goods and supplies",             defaultTerms:"Net 30. Payment due upon receipt of invoice.",                    defaultNotes:"Please confirm receipt and expected delivery date." },
  { id:"po-services",   type:"po", name:"Services PO",                industry:"Professional",       accentColor:"#3B9EFF", description:"Service agreement purchase order for contractors and vendors",     defaultTerms:"Net 30. Services to be completed per attached SOW.",              defaultNotes:"All work must be approved before invoicing." },
  { id:"po-construction",type:"po",name:"Construction Materials PO",  industry:"Construction",       accentColor:"#F59E0B", description:"Materials and supplies for construction projects",                 defaultTerms:"Net 15. Delivery to job site. Proof of delivery required.",       defaultNotes:"Materials must match approved specifications. Substitutions require prior approval." },
  { id:"po-manufacturing",type:"po",name:"Manufacturing / Parts PO",  industry:"Manufacturing",      accentColor:"#A78BFA", description:"Raw materials, parts, and components for production",             defaultTerms:"Net 30. Parts must meet print specifications. PPAP required.",    defaultNotes:"Include material certifications with shipment." },
  { id:"po-tech",       type:"po", name:"Technology / Software PO",   industry:"Technology",         accentColor:"#6366F1", description:"Software licenses, SaaS subscriptions, and hardware",            defaultTerms:"Payment due on activation/delivery. Annual license.",             defaultNotes:"Include license keys and documentation with delivery." },
  { id:"po-maintenance",type:"po", name:"Maintenance & Repair PO",    industry:"Home Services",      accentColor:"#10B981", description:"Maintenance, repair, and service work orders",                    defaultTerms:"Net 15. Invoice upon job completion.",                           defaultNotes:"Photo documentation required before and after." },
  { id:"po-healthcare", type:"po", name:"Healthcare Supplies PO",     industry:"Healthcare",         accentColor:"#EC4899", description:"Medical supplies, equipment, and PPE",                           defaultTerms:"Net 30. Products must meet FDA and HIPAA compliance.",           defaultNotes:"All items must have lot numbers and expiration dates." },
  { id:"po-restaurant", type:"po", name:"Food Service PO",            industry:"Hospitality",        accentColor:"#EF4444", description:"Food, beverage, and restaurant supplies",                        defaultTerms:"COD or Net 7. Perishables must meet temperature standards.",     defaultNotes:"All food items must include packing date." },

  // ── INVOICES ───────────────────────────────────────────────────────────────
  { id:"inv-service",   type:"invoice", name:"Service Invoice",               industry:"General",       accentColor:"#0F172A", description:"Standard service invoice for completed work",              defaultTerms:"Payment due Net 30. Late fee 1.5%/month after due date.",         defaultNotes:"Thank you for your business." },
  { id:"inv-construction",type:"invoice",name:"Construction Progress Invoice",industry:"Construction",  accentColor:"#F59E0B", description:"Progress billing for construction milestones",              defaultTerms:"Payment due upon milestone completion. Lien waiver on payment.", defaultNotes:"This invoice covers work completed through the date shown." },
  { id:"inv-retainer",  type:"invoice", name:"Retainer Invoice",              industry:"Professional",  accentColor:"#3B9EFF", description:"Monthly retainer for ongoing services",                    defaultTerms:"Retainer due 1st of month. Non-refundable.",                     defaultNotes:"Unused hours do not carry over. Additional hours billed at standard rate." },
  { id:"inv-tm",        type:"invoice", name:"Time & Materials Invoice",      industry:"General",       accentColor:"#10B981", description:"Billing for labor hours and materials used",                defaultTerms:"Net 30. All T&M must be pre-authorized.",                        defaultNotes:"Labor and materials breakdown attached." },
  { id:"inv-product",   type:"invoice", name:"Product Invoice",               industry:"Retail",        accentColor:"#A78BFA", description:"Invoice for goods sold and delivered",                     defaultTerms:"Net 30. Returns accepted within 30 days in original packaging.",  defaultNotes:"Inspect all items upon delivery." },
  { id:"inv-subscription",type:"invoice",name:"Subscription / Recurring",     industry:"Technology",   accentColor:"#6366F1", description:"Monthly or annual subscription billing",                    defaultTerms:"Auto-renews. Cancel 30 days before renewal date.",              defaultNotes:"Your subscription covers all users listed in your account." },
  { id:"inv-medical",   type:"invoice", name:"Medical Services Invoice",      industry:"Healthcare",    accentColor:"#EC4899", description:"Patient billing for medical services rendered",             defaultTerms:"Payment due 30 days. Payment plans available.",                  defaultNotes:"Insurance has been billed. This is your portion." },
  { id:"inv-manufacturing",type:"invoice",name:"Manufacturing Job Invoice",   industry:"Manufacturing", accentColor:"#8B5CF6", description:"Invoice for completed job shop work",                      defaultTerms:"Net 30. COA included with shipment.",                            defaultNotes:"Job number and PO referenced above." },

  // ── ESTIMATES ──────────────────────────────────────────────────────────────
  { id:"est-general",   type:"estimate", name:"General Estimate",            industry:"General",       accentColor:"#64748B", description:"General-purpose project estimate",                          defaultTerms:"This estimate is valid for 30 days. Final price may vary.",      defaultNotes:"Prices subject to change upon final scope confirmation." },
  { id:"est-construction",type:"estimate",name:"Construction Bid",           industry:"Construction",  accentColor:"#F59E0B", description:"Formal construction bid with labor and materials",          defaultTerms:"Valid 30 days. Excludes permits and engineering unless noted.",   defaultNotes:"Final price dependent on site conditions and material availability." },
  { id:"est-roofing",   type:"estimate", name:"Roofing & Trades Estimate",   industry:"Home Services", accentColor:"#EF4444", description:"Estimate for roofing, HVAC, plumbing, or electrical work",  defaultTerms:"Estimate valid 14 days. Price subject to material costs.",       defaultNotes:"Additional work discovered during project will require change order." },
  { id:"est-it",        type:"estimate", name:"IT Services Estimate",        industry:"Technology",    accentColor:"#6366F1", description:"Technology project estimate with phases and milestones",     defaultTerms:"Valid 30 days. Scope changes require written approval.",         defaultNotes:"Estimate based on provided requirements. Changes may affect pricing." },
  { id:"est-professional",type:"estimate",name:"Professional Services Est.", industry:"Professional",  accentColor:"#3B9EFF", description:"Consulting, legal, or accounting services estimate",        defaultTerms:"Valid 30 days. Retainer required to begin engagement.",          defaultNotes:"Estimate assumes client will provide all requested information timely." },
  { id:"est-manufacturing",type:"estimate",name:"Manufacturing / Job Shop",  industry:"Manufacturing", accentColor:"#A78BFA", description:"Job shop estimate with material, labor, and burden",        defaultTerms:"Valid 30 days. Tooling quoted separately.",                      defaultNotes:"Final price subject to material verification and print review." },

  // ── RECEIPTS ───────────────────────────────────────────────────────────────
  { id:"rec-service",   type:"receipt", name:"Service Receipt",              industry:"General",       accentColor:"#10B981", description:"Receipt for completed service work",                        defaultTerms:"Thank you. Payment received.",                                   defaultNotes:"Keep this receipt for your records." },
  { id:"rec-materials", type:"receipt", name:"Materials Receipt",            industry:"Construction",  accentColor:"#F59E0B", description:"Receipt for materials or parts received",                  defaultTerms:"Items received in good condition.",                              defaultNotes:"Report any damage within 24 hours." },
  { id:"rec-payment",   type:"receipt", name:"Payment Receipt",              industry:"General",       accentColor:"#3B9EFF", description:"Confirmation of payment received",                          defaultTerms:"Payment received. Balance shown is remaining.",                  defaultNotes:"This receipt confirms your payment has been applied." },
  { id:"rec-misc",      type:"receipt", name:"Miscellaneous Services",       industry:"General",       accentColor:"#94A3B8", description:"Receipt for miscellaneous or ad-hoc services",             defaultTerms:"Thank you for your business.",                                   defaultNotes:"For questions, contact us at the information above." },
];

export const TEMPLATE_TYPES = [
  { id:"po",        label:"Purchase Orders",  icon:"🛒", count:8, color:"#F59E0B" },
  { id:"invoice",   label:"Invoices",         icon:"📄", count:8, color:"#3B9EFF" },
  { id:"estimate",  label:"Estimates",        icon:"📊", count:6, color:"#64748B" },
  { id:"receipt",   label:"Receipts",         icon:"🧾", count:4, color:"#10B981" },
];
